app = "portfolio-tracker-rough-dawn-5271"
primary_region = "fra"

[env]
  PORT = "3000"
  NODE_ENV = "production"

[build]

[deploy]
  release_command = "npm install"


[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[machines]
  size = "shared-cpu-1x"
  memory = "1gb"